@startuml
actor User
participant ":Parser" as Parser
participant ":Executor" as Exec
participant ":AddInternshipCommand" as Cmd
participant ":InternshipList" as List
participant ":Internship" as Intern

User -> Parser : "add Grab /t Software Engineer"
activate Parser
Parser --> Exec : parsed command
deactivate Parser

Exec -> Exec : get command "add"
Exec -> Cmd : execute()
activate Cmd

Cmd -> Parser : getParamsOf(parser.getCommand())
activate Parser
Parser --> Cmd : addParams
deactivate Parser

Cmd -> Parser : getParamsOf("/t")
activate Parser
Parser --> Cmd : titleParams
deactivate Parser

note right of Cmd : Validates company name,\nflag, and title strings

alt missing company name or title
    Cmd -> User : throw GoldenCompassException
else params valid
    create "newInternship:Internship" as Intern
    Cmd -> Intern : new Internship(title, companyName)

    Cmd -> List : add(newInternship)
    activate List
    List --> Cmd
    deactivate List

    Cmd -> Cmd : ui.print("Got it! I've added this internship...")
end

deactivate Cmd
@enduml