@startuml

participant ": ListInterviewCommand" as ListInterviewCommand
participant ": InterviewList" as InterviewList
participant ": Ui" as Ui
participant ": List<Interview>" as L
participant ": Interview" as Interview

activate ListInterviewCommand

ListInterviewCommand -> InterviewList : getInterviews()
activate InterviewList
InterviewList --> ListInterviewCommand : List<Interview> interviews
deactivate InterviewList

alt interviews is empty
    ListInterviewCommand -> Ui : print("You don't have any interviews!")
    activate Ui
    Ui --> ListInterviewCommand
    deactivate Ui

else interviews is nonempty

    ListInterviewCommand -> Ui : print("Here are the interview invitations:")
    activate Ui
    Ui --> ListInterviewCommand
    deactivate Ui

    ListInterviewCommand -> L : stream().sorted().toList()
    activate L
    L --> ListInterviewCommand : sorted_interviews
    deactivate L

    ListInterviewCommand -> L : size()
    activate L
    L --> ListInterviewCommand : size
    deactivate L

    loop for index from 0 to size

        ListInterviewCommand -> L : get(index)
        activate L
        L --> ListInterviewCommand : Interview
        deactivate L

        ListInterviewCommand -> Interview : toString()
        activate Interview
        Interview --> ListInterviewCommand : formatted string
        deactivate Interview

        ListInterviewCommand -> Ui : print(index + ". " + formatted string)
        activate Ui
        Ui --> ListInterviewCommand
        deactivate Ui

    end

end

deactivate ListInterviewCommand

@enduml