@startuml
actor User
participant ":Parser" as Parser
participant ":Executor" as Exec
participant ":MarkOfferCommand" as Cmd
participant ":InternshipList" as List
participant ":Internship" as Intern

User -> Parser : "mark-offer 1"
activate Parser
Parser --> Exec : parsed command
deactivate Parser

Exec -> Exec : get command "mark-offer"
Exec -> Cmd : execute()
activate Cmd

Cmd -> Parser : getParamsOf(parser.getCommand())
activate Parser
Parser --> Cmd : params
deactivate Parser

note right of Cmd : retrieves ["1"]

alt missing index or not a number
    Cmd -> User : throw GoldenCompassException
else index format valid
    Cmd -> List : getSize()
    activate List
    List --> Cmd : size
    deactivate List

    alt index out of range
        Cmd -> User : throw GoldenCompassException
    else index valid
        Cmd -> List : get(index - 1)
        activate List
        List --> Cmd : Internship
        deactivate List

        Cmd -> Intern : markAsOffer()
        activate Intern
        Intern --> Cmd
        deactivate Intern

        Cmd -> Cmd : ui.print("HUGE CONGRATS! Marked this internship...")
    end
end

deactivate Cmd
@enduml