@startuml
actor User
participant ":Ui" as Ui
participant ":GoldenCompass" as GC
participant ":Parser" as Parser
participant ":Executor" as Executor
participant ":SetInterviewDeadlineCommand" as SDC
participant ":InterviewList" as IVL
participant "iv:Interview" as IV

User -> Ui : "update-date 1 /d 2025-04-15 14:00"
activate Ui
Ui --> GC : returns input
deactivate Ui

GC -> Parser : parse("update-date 1 /d 2025-04-15 14:00")
activate Parser
Parser --> GC
deactivate Parser

GC -> Executor : execute()
activate Executor
Executor -> SDC : execute()
activate SDC

SDC -> Parser : getParamsOf("update-date")
activate Parser
Parser --> SDC : ["1"]
deactivate Parser

SDC -> Parser : getParamsOf("/d")
activate Parser
Parser --> SDC : ["2025-04-15 14:00"]
deactivate Parser

SDC -> IVL : isValidIndex(1)
activate IVL
IVL --> SDC : true
deactivate IVL

note right of SDC : Parses "2025-04-15 14:00" into LocalDateTime

SDC -> IVL : getInterviews()
activate IVL
IVL --> SDC : interviews
deactivate IVL

note right of SDC : Sorts interviews by date,\nretrieves interview at index 0

SDC -> IV : setDate(2025-04-15T14:00)
activate IV
IV --> SDC
deactivate IV

SDC -> Ui : print("Deadline set for interview 1: ...")
activate Ui
Ui --> SDC
deactivate Ui

deactivate SDC
deactivate Executor
@enduml
