@startuml
actor User
participant ":GoldenCompass" as GC
participant ":InternshipStorage" as InternStorage
participant ":InterviewStorage" as InterviewStorage
participant ":AliasStorage" as AliasStorage

activate GC
loop while application is running
    User -> GC : inputs command (e.g., "add", "mark")

    note right of GC : Command executes, then\ntriggers eager saving

    GC -> InternStorage : save(internshipList)
    activate InternStorage
    InternStorage -> InternStorage : Write formatting logic
    InternStorage --> GC
    deactivate InternStorage

    GC -> InterviewStorage : save(interviewList)
    activate InterviewStorage
    InterviewStorage -> InterviewStorage : Write formatting logic\n(Extracts Company & Role)
    InterviewStorage --> GC
    deactivate InterviewStorage

    GC -> AliasStorage : save(aliasMap)
    activate AliasStorage
    AliasStorage -> AliasStorage : Write formatting logic
    AliasStorage --> GC
    deactivate AliasStorage

    GC --> User : prints command result
end
deactivate GC
@enduml